version: '3.3'

services:
  wordpress_mysql:
    image: mysql:5.7
    container_name: wordpress_mysql
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_ROOT_PASSWORD: 01%@Yj@yY|&7e2Z612
      MYSQL_PASSWORD: 01%@Yj@yY|&7e2Z612
    ports:
      - "3307:3306"

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - data:/var/www/html
    ports:
      - "8085:80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: wordpress_mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: 01%@Yj@yY|&7e2Z612
    depends_on:
      - wordpress_mysql

volumes:
  mysql_data: {}
  data: {}
